export const CLUB_FIELDS = Object.freeze([
  "Mühendislik ve Mimarlık",
  "Bilgisayar ve Yazılım",
  "Tıp ve Sağlık Bilimleri",
  "Diş Hekimliği",
  "Eczacılık",
  "Hukuk",
  "İktisadi ve İdari Bilimler",
  "İşletme",
  "Eğitim",
  "Fen-Edebiyat",
  "İletişim",
  "Güzel Sanatlar ve Tasarım",
  "Müzik ve Sahne Sanatları",
  "İlahiyat",
  "Spor Bilimleri",
  "Tarım ve Ziraat",
  "Veterinerlik",
  "Turizm",
  "Havacılık ve Uzay",
  "Denizcilik",
  "Psikoloji",
  "Sosyoloji ve Antropoloji",
  "Tarih ve Arkeoloji",
  "Uluslararası İlişkiler ve Siyaset Bilimi",
  "Mütercim Tercümanlık ve Çeviribilim",
  "Gıda Mühendisliği ve Teknolojisi"
]);
