// Tüm ülkelerin arama kodları + ulusal numara uzunlukları (telefon doğrulaması için).
// min/max: ulusal anlamlı numara (trunk ön eki hariç) hane aralığı.
// trunk: ulusal aramada başa eklenen ve uluslararası formatta atılan ön ek ("" = yok).
// Bayrak emojisi ISO kodundan otomatik üretilir (phone-input.js içinde).
const COUNTRY_CODES = [
  { code: "TR", dial: "+90",  name: "Türkiye",                          min: 10, max: 10, trunk: "0" },
  { code: "AF", dial: "+93",  name: "Afghanistan",                      min: 9,  max: 9,  trunk: "0" },
  { code: "AL", dial: "+355", name: "Albania",                          min: 9,  max: 9,  trunk: "0" },
  { code: "DZ", dial: "+213", name: "Algeria",                          min: 9,  max: 9,  trunk: "0" },
  { code: "AD", dial: "+376", name: "Andorra",                          min: 6,  max: 6,  trunk: ""  },
  { code: "AO", dial: "+244", name: "Angola",                           min: 9,  max: 9,  trunk: ""  },
  { code: "AG", dial: "+1",   name: "Antigua and Barbuda",              min: 10, max: 10, trunk: "1" },
  { code: "AR", dial: "+54",  name: "Argentina",                        min: 10, max: 10, trunk: "0" },
  { code: "AM", dial: "+374", name: "Armenia",                          min: 8,  max: 8,  trunk: "0" },
  { code: "AU", dial: "+61",  name: "Australia",                        min: 9,  max: 9,  trunk: "0" },
  { code: "AT", dial: "+43",  name: "Austria",                          min: 10, max: 11, trunk: "0" },
  { code: "AZ", dial: "+994", name: "Azerbaijan",                       min: 9,  max: 9,  trunk: "0" },
  { code: "BS", dial: "+1",   name: "Bahamas",                          min: 10, max: 10, trunk: "1" },
  { code: "BH", dial: "+973", name: "Bahrain",                          min: 8,  max: 8,  trunk: ""  },
  { code: "BD", dial: "+880", name: "Bangladesh",                       min: 10, max: 10, trunk: "0" },
  { code: "BB", dial: "+1",   name: "Barbados",                         min: 10, max: 10, trunk: "1" },
  { code: "BY", dial: "+375", name: "Belarus",                          min: 9,  max: 9,  trunk: "0" },
  { code: "BE", dial: "+32",  name: "Belgium",                          min: 9,  max: 9,  trunk: "0" },
  { code: "BZ", dial: "+501", name: "Belize",                           min: 7,  max: 7,  trunk: ""  },
  { code: "BJ", dial: "+229", name: "Benin",                            min: 8,  max: 8,  trunk: ""  },
  { code: "BT", dial: "+975", name: "Bhutan",                           min: 8,  max: 8,  trunk: ""  },
  { code: "BO", dial: "+591", name: "Bolivia",                          min: 8,  max: 8,  trunk: ""  },
  { code: "BA", dial: "+387", name: "Bosnia and Herzegovina",          min: 8,  max: 8,  trunk: "0" },
  { code: "BW", dial: "+267", name: "Botswana",                         min: 8,  max: 8,  trunk: ""  },
  { code: "BR", dial: "+55",  name: "Brazil",                           min: 10, max: 11, trunk: "0" },
  { code: "BN", dial: "+673", name: "Brunei",                           min: 7,  max: 7,  trunk: ""  },
  { code: "BG", dial: "+359", name: "Bulgaria",                         min: 9,  max: 9,  trunk: "0" },
  { code: "BF", dial: "+226", name: "Burkina Faso",                     min: 8,  max: 8,  trunk: ""  },
  { code: "BI", dial: "+257", name: "Burundi",                          min: 8,  max: 8,  trunk: ""  },
  { code: "KH", dial: "+855", name: "Cambodia",                         min: 8,  max: 9,  trunk: "0" },
  { code: "CM", dial: "+237", name: "Cameroon",                         min: 9,  max: 9,  trunk: ""  },
  { code: "CA", dial: "+1",   name: "Canada",                           min: 10, max: 10, trunk: "1" },
  { code: "CV", dial: "+238", name: "Cape Verde",                       min: 7,  max: 7,  trunk: ""  },
  { code: "CF", dial: "+236", name: "Central African Republic",        min: 8,  max: 8,  trunk: ""  },
  { code: "TD", dial: "+235", name: "Chad",                             min: 8,  max: 8,  trunk: ""  },
  { code: "CL", dial: "+56",  name: "Chile",                            min: 9,  max: 9,  trunk: "0" },
  { code: "CN", dial: "+86",  name: "China",                            min: 11, max: 11, trunk: "0" },
  { code: "CO", dial: "+57",  name: "Colombia",                         min: 10, max: 10, trunk: "0" },
  { code: "KM", dial: "+269", name: "Comoros",                          min: 7,  max: 7,  trunk: ""  },
  { code: "CG", dial: "+242", name: "Congo (Republic)",                min: 9,  max: 9,  trunk: ""  },
  { code: "CD", dial: "+243", name: "Congo (DRC)",                      min: 9,  max: 9,  trunk: "0" },
  { code: "CR", dial: "+506", name: "Costa Rica",                       min: 8,  max: 8,  trunk: ""  },
  { code: "CI", dial: "+225", name: "Côte d'Ivoire",                    min: 10, max: 10, trunk: ""  },
  { code: "HR", dial: "+385", name: "Croatia",                          min: 8,  max: 9,  trunk: "0" },
  { code: "CU", dial: "+53",  name: "Cuba",                             min: 8,  max: 8,  trunk: "0" },
  { code: "CY", dial: "+357", name: "Cyprus",                           min: 8,  max: 8,  trunk: ""  },
  { code: "CZ", dial: "+420", name: "Czechia",                          min: 9,  max: 9,  trunk: ""  },
  { code: "DK", dial: "+45",  name: "Denmark",                          min: 8,  max: 8,  trunk: ""  },
  { code: "DJ", dial: "+253", name: "Djibouti",                         min: 8,  max: 8,  trunk: ""  },
  { code: "DM", dial: "+1",   name: "Dominica",                         min: 10, max: 10, trunk: "1" },
  { code: "DO", dial: "+1",   name: "Dominican Republic",              min: 10, max: 10, trunk: "1" },
  { code: "EC", dial: "+593", name: "Ecuador",                          min: 9,  max: 9,  trunk: "0" },
  { code: "EG", dial: "+20",  name: "Egypt",                            min: 10, max: 10, trunk: "0" },
  { code: "SV", dial: "+503", name: "El Salvador",                      min: 8,  max: 8,  trunk: ""  },
  { code: "GQ", dial: "+240", name: "Equatorial Guinea",               min: 9,  max: 9,  trunk: ""  },
  { code: "ER", dial: "+291", name: "Eritrea",                          min: 7,  max: 7,  trunk: "0" },
  { code: "EE", dial: "+372", name: "Estonia",                          min: 7,  max: 8,  trunk: ""  },
  { code: "SZ", dial: "+268", name: "Eswatini",                         min: 8,  max: 8,  trunk: ""  },
  { code: "ET", dial: "+251", name: "Ethiopia",                         min: 9,  max: 9,  trunk: "0" },
  { code: "FJ", dial: "+679", name: "Fiji",                             min: 7,  max: 7,  trunk: ""  },
  { code: "FI", dial: "+358", name: "Finland",                          min: 9,  max: 10, trunk: "0" },
  { code: "FR", dial: "+33",  name: "France",                           min: 9,  max: 9,  trunk: "0" },
  { code: "GA", dial: "+241", name: "Gabon",                            min: 8,  max: 8,  trunk: ""  },
  { code: "GM", dial: "+220", name: "Gambia",                           min: 7,  max: 7,  trunk: ""  },
  { code: "GE", dial: "+995", name: "Georgia",                          min: 9,  max: 9,  trunk: "0" },
  { code: "DE", dial: "+49",  name: "Germany",                          min: 10, max: 11, trunk: "0" },
  { code: "GH", dial: "+233", name: "Ghana",                            min: 9,  max: 9,  trunk: "0" },
  { code: "GR", dial: "+30",  name: "Greece",                           min: 10, max: 10, trunk: ""  },
  { code: "GL", dial: "+299", name: "Greenland",                        min: 6,  max: 6,  trunk: ""  },
  { code: "GD", dial: "+1",   name: "Grenada",                          min: 10, max: 10, trunk: "1" },
  { code: "GT", dial: "+502", name: "Guatemala",                        min: 8,  max: 8,  trunk: ""  },
  { code: "GN", dial: "+224", name: "Guinea",                           min: 9,  max: 9,  trunk: ""  },
  { code: "GW", dial: "+245", name: "Guinea-Bissau",                    min: 9,  max: 9,  trunk: ""  },
  { code: "GY", dial: "+592", name: "Guyana",                           min: 7,  max: 7,  trunk: ""  },
  { code: "HT", dial: "+509", name: "Haiti",                            min: 8,  max: 8,  trunk: ""  },
  { code: "HN", dial: "+504", name: "Honduras",                         min: 8,  max: 8,  trunk: ""  },
  { code: "HK", dial: "+852", name: "Hong Kong",                        min: 8,  max: 8,  trunk: ""  },
  { code: "HU", dial: "+36",  name: "Hungary",                          min: 9,  max: 9,  trunk: "0" },
  { code: "IS", dial: "+354", name: "Iceland",                          min: 7,  max: 7,  trunk: ""  },
  { code: "IN", dial: "+91",  name: "India",                            min: 10, max: 10, trunk: "0" },
  { code: "ID", dial: "+62",  name: "Indonesia",                        min: 9,  max: 12, trunk: "0" },
  { code: "IR", dial: "+98",  name: "Iran",                             min: 10, max: 10, trunk: "0" },
  { code: "IQ", dial: "+964", name: "Iraq",                             min: 10, max: 10, trunk: "0" },
  { code: "IE", dial: "+353", name: "Ireland",                          min: 9,  max: 9,  trunk: "0" },
  { code: "IL", dial: "+972", name: "Israel",                           min: 9,  max: 9,  trunk: "0" },
  { code: "IT", dial: "+39",  name: "Italy",                            min: 9,  max: 10, trunk: ""  },
  { code: "JM", dial: "+1",   name: "Jamaica",                          min: 10, max: 10, trunk: "1" },
  { code: "JP", dial: "+81",  name: "Japan",                            min: 10, max: 10, trunk: "0" },
  { code: "JO", dial: "+962", name: "Jordan",                           min: 9,  max: 9,  trunk: "0" },
  { code: "KZ", dial: "+7",   name: "Kazakhstan",                       min: 10, max: 10, trunk: "8" },
  { code: "KE", dial: "+254", name: "Kenya",                            min: 9,  max: 9,  trunk: "0" },
  { code: "KI", dial: "+686", name: "Kiribati",                         min: 8,  max: 8,  trunk: ""  },
  { code: "XK", dial: "+383", name: "Kosovo",                           min: 8,  max: 8,  trunk: "0" },
  { code: "KW", dial: "+965", name: "Kuwait",                           min: 8,  max: 8,  trunk: ""  },
  { code: "KG", dial: "+996", name: "Kyrgyzstan",                       min: 9,  max: 9,  trunk: "0" },
  { code: "LA", dial: "+856", name: "Laos",                             min: 9,  max: 10, trunk: "0" },
  { code: "LV", dial: "+371", name: "Latvia",                           min: 8,  max: 8,  trunk: ""  },
  { code: "LB", dial: "+961", name: "Lebanon",                          min: 7,  max: 8,  trunk: "0" },
  { code: "LS", dial: "+266", name: "Lesotho",                          min: 8,  max: 8,  trunk: ""  },
  { code: "LR", dial: "+231", name: "Liberia",                          min: 8,  max: 9,  trunk: "0" },
  { code: "LY", dial: "+218", name: "Libya",                            min: 9,  max: 9,  trunk: "0" },
  { code: "LI", dial: "+423", name: "Liechtenstein",                    min: 7,  max: 7,  trunk: ""  },
  { code: "LT", dial: "+370", name: "Lithuania",                        min: 8,  max: 8,  trunk: "0" },
  { code: "LU", dial: "+352", name: "Luxembourg",                       min: 9,  max: 9,  trunk: ""  },
  { code: "MO", dial: "+853", name: "Macau",                            min: 8,  max: 8,  trunk: ""  },
  { code: "MG", dial: "+261", name: "Madagascar",                       min: 9,  max: 9,  trunk: "0" },
  { code: "MW", dial: "+265", name: "Malawi",                           min: 9,  max: 9,  trunk: "0" },
  { code: "MY", dial: "+60",  name: "Malaysia",                         min: 9,  max: 10, trunk: "0" },
  { code: "MV", dial: "+960", name: "Maldives",                         min: 7,  max: 7,  trunk: ""  },
  { code: "ML", dial: "+223", name: "Mali",                             min: 8,  max: 8,  trunk: ""  },
  { code: "MT", dial: "+356", name: "Malta",                            min: 8,  max: 8,  trunk: ""  },
  { code: "MH", dial: "+692", name: "Marshall Islands",                min: 7,  max: 7,  trunk: ""  },
  { code: "MR", dial: "+222", name: "Mauritania",                       min: 8,  max: 8,  trunk: ""  },
  { code: "MU", dial: "+230", name: "Mauritius",                        min: 8,  max: 8,  trunk: ""  },
  { code: "MX", dial: "+52",  name: "Mexico",                           min: 10, max: 10, trunk: "0" },
  { code: "FM", dial: "+691", name: "Micronesia",                       min: 7,  max: 7,  trunk: ""  },
  { code: "MD", dial: "+373", name: "Moldova",                          min: 8,  max: 8,  trunk: "0" },
  { code: "MC", dial: "+377", name: "Monaco",                           min: 8,  max: 9,  trunk: ""  },
  { code: "MN", dial: "+976", name: "Mongolia",                         min: 8,  max: 8,  trunk: ""  },
  { code: "ME", dial: "+382", name: "Montenegro",                       min: 8,  max: 8,  trunk: "0" },
  { code: "MA", dial: "+212", name: "Morocco",                          min: 9,  max: 9,  trunk: "0" },
  { code: "MZ", dial: "+258", name: "Mozambique",                       min: 9,  max: 9,  trunk: ""  },
  { code: "MM", dial: "+95",  name: "Myanmar",                          min: 8,  max: 10, trunk: "0" },
  { code: "NA", dial: "+264", name: "Namibia",                          min: 9,  max: 9,  trunk: "0" },
  { code: "NR", dial: "+674", name: "Nauru",                            min: 7,  max: 7,  trunk: ""  },
  { code: "NP", dial: "+977", name: "Nepal",                            min: 10, max: 10, trunk: "0" },
  { code: "NL", dial: "+31",  name: "Netherlands",                      min: 9,  max: 9,  trunk: "0" },
  { code: "NZ", dial: "+64",  name: "New Zealand",                      min: 8,  max: 10, trunk: "0" },
  { code: "NI", dial: "+505", name: "Nicaragua",                        min: 8,  max: 8,  trunk: ""  },
  { code: "NE", dial: "+227", name: "Niger",                            min: 8,  max: 8,  trunk: ""  },
  { code: "NG", dial: "+234", name: "Nigeria",                          min: 10, max: 10, trunk: "0" },
  { code: "KP", dial: "+850", name: "North Korea",                      min: 9,  max: 10, trunk: "0" },
  { code: "MK", dial: "+389", name: "North Macedonia",                  min: 8,  max: 8,  trunk: "0" },
  { code: "NO", dial: "+47",  name: "Norway",                           min: 8,  max: 8,  trunk: ""  },
  { code: "OM", dial: "+968", name: "Oman",                             min: 8,  max: 8,  trunk: ""  },
  { code: "PK", dial: "+92",  name: "Pakistan",                         min: 10, max: 10, trunk: "0" },
  { code: "PW", dial: "+680", name: "Palau",                            min: 7,  max: 7,  trunk: ""  },
  { code: "PS", dial: "+970", name: "Palestine",                        min: 9,  max: 9,  trunk: "0" },
  { code: "PA", dial: "+507", name: "Panama",                           min: 8,  max: 8,  trunk: ""  },
  { code: "PG", dial: "+675", name: "Papua New Guinea",                min: 8,  max: 8,  trunk: ""  },
  { code: "PY", dial: "+595", name: "Paraguay",                         min: 9,  max: 9,  trunk: "0" },
  { code: "PE", dial: "+51",  name: "Peru",                             min: 9,  max: 9,  trunk: "0" },
  { code: "PH", dial: "+63",  name: "Philippines",                      min: 10, max: 10, trunk: "0" },
  { code: "PL", dial: "+48",  name: "Poland",                           min: 9,  max: 9,  trunk: ""  },
  { code: "PT", dial: "+351", name: "Portugal",                         min: 9,  max: 9,  trunk: ""  },
  { code: "PR", dial: "+1",   name: "Puerto Rico",                      min: 10, max: 10, trunk: "1" },
  { code: "QA", dial: "+974", name: "Qatar",                            min: 8,  max: 8,  trunk: ""  },
  { code: "RO", dial: "+40",  name: "Romania",                          min: 9,  max: 9,  trunk: "0" },
  { code: "RU", dial: "+7",   name: "Russia",                           min: 10, max: 10, trunk: "8" },
  { code: "RW", dial: "+250", name: "Rwanda",                           min: 9,  max: 9,  trunk: "0" },
  { code: "KN", dial: "+1",   name: "Saint Kitts and Nevis",           min: 10, max: 10, trunk: "1" },
  { code: "LC", dial: "+1",   name: "Saint Lucia",                      min: 10, max: 10, trunk: "1" },
  { code: "VC", dial: "+1",   name: "Saint Vincent and the Grenadines",min: 10, max: 10, trunk: "1" },
  { code: "WS", dial: "+685", name: "Samoa",                            min: 7,  max: 7,  trunk: ""  },
  { code: "SM", dial: "+378", name: "San Marino",                       min: 10, max: 10, trunk: ""  },
  { code: "ST", dial: "+239", name: "Sao Tome and Principe",           min: 7,  max: 7,  trunk: ""  },
  { code: "SA", dial: "+966", name: "Saudi Arabia",                     min: 9,  max: 9,  trunk: "0" },
  { code: "SN", dial: "+221", name: "Senegal",                          min: 9,  max: 9,  trunk: ""  },
  { code: "RS", dial: "+381", name: "Serbia",                           min: 8,  max: 9,  trunk: "0" },
  { code: "SC", dial: "+248", name: "Seychelles",                       min: 7,  max: 7,  trunk: ""  },
  { code: "SL", dial: "+232", name: "Sierra Leone",                     min: 8,  max: 8,  trunk: "0" },
  { code: "SG", dial: "+65",  name: "Singapore",                        min: 8,  max: 8,  trunk: ""  },
  { code: "SK", dial: "+421", name: "Slovakia",                         min: 9,  max: 9,  trunk: "0" },
  { code: "SI", dial: "+386", name: "Slovenia",                         min: 8,  max: 8,  trunk: "0" },
  { code: "SB", dial: "+677", name: "Solomon Islands",                  min: 7,  max: 7,  trunk: ""  },
  { code: "SO", dial: "+252", name: "Somalia",                          min: 8,  max: 8,  trunk: ""  },
  { code: "ZA", dial: "+27",  name: "South Africa",                     min: 9,  max: 9,  trunk: "0" },
  { code: "KR", dial: "+82",  name: "South Korea",                      min: 9,  max: 10, trunk: "0" },
  { code: "SS", dial: "+211", name: "South Sudan",                      min: 9,  max: 9,  trunk: "0" },
  { code: "ES", dial: "+34",  name: "Spain",                            min: 9,  max: 9,  trunk: ""  },
  { code: "LK", dial: "+94",  name: "Sri Lanka",                        min: 9,  max: 9,  trunk: "0" },
  { code: "SD", dial: "+249", name: "Sudan",                            min: 9,  max: 9,  trunk: "0" },
  { code: "SR", dial: "+597", name: "Suriname",                         min: 7,  max: 7,  trunk: ""  },
  { code: "SE", dial: "+46",  name: "Sweden",                           min: 9,  max: 9,  trunk: "0" },
  { code: "CH", dial: "+41",  name: "Switzerland",                      min: 9,  max: 9,  trunk: "0" },
  { code: "SY", dial: "+963", name: "Syria",                            min: 9,  max: 9,  trunk: "0" },
  { code: "TW", dial: "+886", name: "Taiwan",                           min: 9,  max: 9,  trunk: "0" },
  { code: "TJ", dial: "+992", name: "Tajikistan",                       min: 9,  max: 9,  trunk: "0" },
  { code: "TZ", dial: "+255", name: "Tanzania",                         min: 9,  max: 9,  trunk: "0" },
  { code: "TH", dial: "+66",  name: "Thailand",                         min: 9,  max: 9,  trunk: "0" },
  { code: "TL", dial: "+670", name: "Timor-Leste",                      min: 8,  max: 8,  trunk: ""  },
  { code: "TG", dial: "+228", name: "Togo",                             min: 8,  max: 8,  trunk: ""  },
  { code: "TO", dial: "+676", name: "Tonga",                            min: 7,  max: 7,  trunk: ""  },
  { code: "TT", dial: "+1",   name: "Trinidad and Tobago",             min: 10, max: 10, trunk: "1" },
  { code: "TN", dial: "+216", name: "Tunisia",                          min: 8,  max: 8,  trunk: ""  },
  { code: "TM", dial: "+993", name: "Turkmenistan",                     min: 8,  max: 8,  trunk: "0" },
  { code: "TV", dial: "+688", name: "Tuvalu",                           min: 6,  max: 6,  trunk: ""  },
  { code: "UG", dial: "+256", name: "Uganda",                           min: 9,  max: 9,  trunk: "0" },
  { code: "UA", dial: "+380", name: "Ukraine",                          min: 9,  max: 9,  trunk: "0" },
  { code: "AE", dial: "+971", name: "United Arab Emirates",            min: 9,  max: 9,  trunk: "0" },
  { code: "GB", dial: "+44",  name: "United Kingdom",                   min: 10, max: 10, trunk: "0" },
  { code: "US", dial: "+1",   name: "United States",                    min: 10, max: 10, trunk: "1" },
  { code: "UY", dial: "+598", name: "Uruguay",                          min: 8,  max: 8,  trunk: "0" },
  { code: "UZ", dial: "+998", name: "Uzbekistan",                       min: 9,  max: 9,  trunk: "0" },
  { code: "VU", dial: "+678", name: "Vanuatu",                          min: 7,  max: 7,  trunk: ""  },
  { code: "VA", dial: "+379", name: "Vatican City",                     min: 10, max: 10, trunk: ""  },
  { code: "VE", dial: "+58",  name: "Venezuela",                        min: 10, max: 10, trunk: "0" },
  { code: "VN", dial: "+84",  name: "Vietnam",                          min: 9,  max: 10, trunk: "0" },
  { code: "YE", dial: "+967", name: "Yemen",                            min: 9,  max: 9,  trunk: "0" },
  { code: "ZM", dial: "+260", name: "Zambia",                           min: 9,  max: 9,  trunk: "0" },
  { code: "ZW", dial: "+263", name: "Zimbabwe",                         min: 9,  max: 9,  trunk: "0" }
];

const DEFAULT_COUNTRY = "TR";

export { COUNTRY_CODES, DEFAULT_COUNTRY };
