export const COMMON_DEPARTMENTS = Object.freeze([
  "Abaza Dili ve Edebiyatı",
  "Acil Durum ve Afet Yönetimi",
  "Acil Yardım ve Afet Yönetimi",
  "Adli Bilimler",
  "Adli Bilişim Mühendisliği",
  "Aktüerya Bilimleri",
  "Akıllı Altyapılar Teknikerliği",
  "Akıllı Sera Teknolojileri",
  "Akıllı Tarım ve Gıda Yönetimi",
  "Alman Dili ve Edebiyatı",
  "Almanca Mütercim ve Tercümanlık",
  "Almanca Öğretmenliği",
  "Alternatif Enerji Kaynakları Teknolojisi",
  "Ameliyathane Hizmetleri",
  "Amerikan Kültürü ve Edebiyatı",
  "Anestezi",
  "Antrenörlük Eğitimi",
  "Antropoloji",
  "Arap Dili ve Edebiyatı",
  "Arapça Mütercim ve Tercümanlık",
  "Arapça Öğretmenliği",
  "Arka-Yüz Yazılım Geliştirme",
  "Arkeoloji",
  "Arkeoloji ve Sanat Tarihi",
  "Arnavut Dili ve Edebiyatı",
  "Arıcılık",
  "Astronomi ve Uzay Bilimleri",
  "Atçılık ve Antrenörlüğü",
  "Avcılık ve Yaban Hayatı",
  "Ayakkabı Tasarım ve Üretimi",
  "Ayakkabı Tasarımı ve Üretimi",
  "Azerbaycan Türkçesi ve Edebiyatı",
  "Açık Deniz Sondaj Teknolojisi",
  "Açık Deniz Tabanı Uygulamaları Teknolojisi",
  "Ağaç İşleri Endüstri Mühendisliği",
  "Ağız ve Diş Sağlığı",
  "Aşçılık",
  "Bahçe Bitkileri",
  "Bahçe Tarımı",
  "Balıkçılık Teknolojisi Mühendisliği",
  "Bankacılık",
  "Bankacılık ve Sigortacılık",
  "Basım Teknolojileri",
  "Basım ve Yayım Teknolojileri",
  "Basın ve Yayın",
  "Bağcılık",
  "Bağcılık ve Bağ Ürünleri Teknolojisi",
  "Beden Eğitimi ve Spor Öğretmenliği",
  "Beslenme ve Diyetetik",
  "Bilgi Güvenliği Teknolojisi",
  "Bilgi ve Belge Yönetimi",
  "Bilgisayar Bilimleri",
  "Bilgisayar Destekli Tasarım ve Animasyon",
  "Bilgisayar Mühendisliği",
  "Bilgisayar Operatörlüğü",
  "Bilgisayar Programcılığı",
  "Bilgisayar Teknolojisi",
  "Bilgisayar Teknolojisi ve Bilişim Sistemleri",
  "Bilgisayar ve Öğretim Teknolojileri Öğretmenliği",
  "Bilim Tarihi",
  "Bilişim Güvenliği Teknolojisi",
  "Bilişim Sistemleri Mühendisliği",
  "Bilişim Sistemleri ve Teknolojileri",
  "Bilişim Teknolojileri Öğretmenliği",
  "Bitki Koruma",
  "Bitkisel Üretim ve Teknolojileri",
  "Biyokimya",
  "Biyoloji",
  "Biyoloji Öğretmenliği",
  "Biyomedikal Cihaz Teknolojisi",
  "Biyomedikal Mühendisliği",
  "Biyomühendislik",
  "Biyosistem Mühendisliği",
  "Biyoteknoloji",
  "Biyoteknoloji ve Genetik",
  "Boya Teknolojisi",
  "Boşnak Dili ve Edebiyatı",
  "Bulgar Dili ve Edebiyatı",
  "Bulgarca Mütercim ve Tercümanlık",
  "Bulut Bilişim Operatörlüğü",
  "Büro Yönetimi ve Yönetici Asistanlığı",
  "Büyük Veri Analistliği",
  "Bıçakçılık ve El Aletleri Üretim Teknolojisi",
  "Cevher Hazırlama Mühendisliği",
  "Ceza İnfaz ve Güvenlik Hizmetleri",
  "Cnc Programlama ve Operatörlüğü",
  "Coğrafi Bilgi Sistemleri",
  "Coğrafya",
  "Coğrafya Öğretmenliği",
  "Deniz Brokerliği",
  "Deniz Ulaştırma İşletme Mühendisliği",
  "Deniz Ulaştırma ve İşletme",
  "Deniz ve Liman İşletmeciliği",
  "Denizcilik İşletmeleri Yönetimi",
  "Deri Mühendisliği",
  "Deri Teknolojisi",
  "Dezenfeksiyon, Sterilizasyon ve Antisepsi Teknikerliği",
  "Dijital Dönüşüm Elektroniği",
  "Dijital Fabrika Teknolojileri",
  "Dijital Oyun Tasarımı",
  "Dijital Sağlık Sistemleri Teknikerliği",
  "Dijital Tarım Teknolojileri",
  "Dil ve Konuşma Terapisi",
  "Dilbilimi",
  "Diyaliz",
  "Diş Hekimliği",
  "Diş Protez Teknolojisi",
  "Doğa Koruma ve Biyoçeşitlilik Yönetimi",
  "Doğal Yapı Taşları Teknolojisi",
  "Doğalgaz ve Tesisatı Teknolojisi",
  "Döküm",
  "Dış Ticaret",
  "E-Ticaret ve Pazarlama",
  "Ebelik",
  "Eczacılık",
  "Eczane Hizmetleri",
  "Egzersiz ve Spor Bilimleri",
  "Ekonometri",
  "Ekonomi",
  "Ekonomi ve Finans",
  "El Sanatları",
  "Elektrik",
  "Elektrik Enerjisi Üretim, İletim ve Dağıtımı",
  "Elektrik Makineleri Bakım ve Onarımı",
  "Elektrik Mühendisliği",
  "Elektrik-Elektronik Mühendisliği",
  "Elektrikli Cihaz Teknolojisi",
  "Elektronik Haberleşme Teknolojisi",
  "Elektronik Mühendisliği",
  "Elektronik Teknolojisi",
  "Elektronik Ticaret ve Yönetimi",
  "Elektronik ve Haberleşme Mühendisliği",
  "Elektronörofizyoloji",
  "Emlak Yönetimi",
  "Endüstri Mühendisliği",
  "Endüstri Ürünleri Tasarımı",
  "Endüstriyel Cam ve Seramik",
  "Endüstriyel Hammaddeler İşleme Teknolojisi",
  "Endüstriyel Kalıpçılık",
  "Endüstriyel Tasarım",
  "Endüstriyel Tasarım Mühendisliği",
  "Enerji Bilimi ve Teknolojileri",
  "Enerji Sistemleri Mühendisliği",
  "Enerji Tesisleri İşletmeciliği",
  "Enerji Yönetimi",
  "Engelli Bakımı ve Rehabilitasyon",
  "Engelliler İçin Gölge Öğreticilik",
  "Ergoterapi",
  "Ermeni Dili ve Kültürü",
  "Eser Koruma",
  "Eski Yunan Dili ve Edebiyatı",
  "Et ve Ürünleri Teknolojisi",
  "Evde Hasta Bakımı",
  "Fars Dili ve Edebiyatı",
  "Farsça Mütercim ve Tercümanlık",
  "Felsefe",
  "Felsefe Grubu Öğretmenliği",
  "Fen Bilgisi Öğretmenliği",
  "Fiber Tekne İmalatı ve Kompozit Kalıp Teknolojileri",
  "Fidan Yetiştiriciliği",
  "Film Tasarımı ve Yazarlığı",
  "Film Tasarımı ve Yönetimi",
  "Finans ve Bankacılık",
  "Fizik",
  "Fizik Mühendisliği",
  "Fizik Öğretmenliği",
  "Fizyoterapi",
  "Fizyoterapi ve Rehabilitasyon",
  "Fotonik",
  "Fotoğraf",
  "Fotoğraf ve Video",
  "Fotoğrafçılık ve Kameramanlık",
  "Fransız Dili ve Edebiyatı",
  "Fransızca Mütercim ve Tercümanlık",
  "Fransızca Öğretmenliği",
  "Fındık Eksperliği",
  "Gastronomi ve Mutfak Sanatları",
  "Gayrimenkul Geliştirme ve Yönetimi",
  "Gayrimenkul ve Varlık Yönetimi",
  "Gazetecilik",
  "Geleneksel El Sanatları",
  "Geleneksel Tekstillerin Korunması ve Restorasyonu",
  "Geleneksel Türk Sanatları",
  "Gemi İnşaatı",
  "Gemi İnşaatı ve Gemi Makineleri Mühendisliği",
  "Gemi Makineleri İşletme Mühendisliği",
  "Gemi Makineleri İşletmeciliği",
  "Gemi ve Deniz Teknolojisi Mühendisliği",
  "Gemi ve Yat Tasarımı",
  "Genetik ve Biyomühendislik",
  "Geoteknik",
  "Gerontoloji",
  "Giyim Üretim Teknolojisi",
  "Grafik",
  "Grafik Sanatlar",
  "Grafik Tasarımı",
  "Görsel İletişim",
  "Görsel İletişim Tasarımı",
  "Görsel Sanatlar Öğretmenliği",
  "Gümrük İşletme",
  "Gürcü Dili ve Edebiyatı",
  "Gıda Kalite Kontrolü ve Analizi",
  "Gıda Mühendisliği",
  "Gıda Teknolojisi",
  "Halkbilimi",
  "Halkla İlişkiler ve Reklamcılık",
  "Halkla İlişkiler ve Tanıtım",
  "Halıcılık ve Kilimcilik",
  "Harita Mühendisliği",
  "Harita ve Kadastro",
  "Hassas Tarım ve Tarımsal Robotlar",
  "Hasta Bakımı",
  "Hava Aracı İmalat Teknolojileri",
  "Hava Lojistiği",
  "Havacılık Elektrik ve Elektroniği",
  "Havacılık Elektroniği Teknolojileri",
  "Havacılık ve Uzay Mühendisliği",
  "Havacılık Yönetimi",
  "Hayvansal Üretim ve Teknolojileri",
  "Hemşirelik",
  "Heykel",
  "Hibrid ve Elektrikli Taşıtlar Teknolojisi",
  "Hidrojen ve Enerji Depolama Teknikerliği",
  "Hidrojeoloji Mühendisliği",
  "Hidrolik ve Pnömatik Teknikerliği",
  "Hindoloji",
  "Hititoloji",
  "Hukuk",
  "Hungaroloji",
  "İbrani Dili ve Kültürü",
  "İklim Bilimi ve Meteoroloji Mühendisliği",
  "İklimlendirme ve Soğutma Teknolojisi",
  "İkram Hizmetleri",
  "İktisat",
  "İlahiyat",
  "İletişim",
  "İletişim Bilimleri",
  "İletişim Tasarımı ve Yönetimi",
  "İletişim ve Tasarımı",
  "İlk ve Acil Yardım",
  "İlköğretim Matematik Öğretmenliği",
  "İmalat Mühendisliği",
  "İmalat Yürütme Sistemleri Operatörlüğü",
  "İngiliz Dilbilimi",
  "İngiliz Dili ve Edebiyatı",
  "İngilizce Mütercim ve Tercümanlık",
  "İngilizce Öğretmenliği",
  "İngilizce, Fransızca Mütercim ve Tercümanlık",
  "İnsan Kaynakları Yönetimi",
  "İnsansız Araç Teknikerliği",
  "İnsansız Hava Aracı Teknolojisi ve Operatörlüğü",
  "İnterior Mimarlık",
  "İnternet ve Ağ Teknolojileri",
  "İnşaat Mühendisliği",
  "İnşaat Teknolojisi",
  "İslam İktisadı ve Finans",
  "İslami İlimler",
  "İspanyol Dili ve Edebiyatı",
  "İspanyolca Mütercim ve Tercümanlık",
  "İstatistik",
  "İstatistik ve Bilgisayar Bilimleri",
  "İtalyan Dili ve Edebiyatı",
  "İç Mekan Tasarımı",
  "İç Mimarlık",
  "İç Mimarlık ve Çevre Tasarımı",
  "İş Makineleri Operatörlüğü",
  "İş Sağlığı ve Güvenliği",
  "İş ve Uğraşı Terapisi",
  "İşletme",
  "İşletme Mühendisliği",
  "İşletme ve Yapay Zeka",
  "İşletme Yönetimi",
  "Japon Dili ve Edebiyatı",
  "Japonca Mütercim ve Tercümanlık",
  "Japonca Öğretmenliği",
  "Jeofizik Mühendisliği",
  "Jeoloji Mühendisliği",
  "Kamu Yönetimi",
  "Kanatlı Hayvan Yetiştiriciliği",
  "Karayolu Yük Taşıtı Sürücülüğü",
  "Karbon Yönetimi Teknikerliği",
  "Karşılaştırmalı Edebiyat",
  "Kaynak Teknolojisi",
  "Kenevir Dokumacılığı",
  "Kentsel Tasarım ve Peyzaj Mimarlığı",
  "Kimya",
  "Kimya Mühendisliği",
  "Kimya Teknolojisi",
  "Kimya Öğretmenliği",
  "Kimya-Biyoloji Mühendisliği",
  "Klasik Arkeoloji",
  "Konaklama İşletmeciliği",
  "Kontrol ve Otomasyon Mühendisliği",
  "Kontrol ve Otomasyon Teknolojisi",
  "Kooperatifçilik",
  "Kore Dili ve Edebiyatı",
  "Kozmetik Teknolojisi",
  "Kurgu, Ses ve Görüntü Yönetimi",
  "Kurumsal Bilişim Uzmanlığı",
  "Kuyumculuk ve Mücevher Tasarımı",
  "Kuyumculuk ve Takı Tasarımı",
  "Kültür Varlıklarını Koruma ve Onarım",
  "Kültür ve İletişim Bilimleri",
  "Kültürel Miras ve Turizm",
  "Kümes Hayvanları Yetiştiriciliği",
  "Küresel Siyaset ve Uluslararası İlişkiler",
  "Kürt Dili ve Edebiyatı",
  "Laborant ve Veteriner Sağlık",
  "Laboratuvar Teknolojisi",
  "Latin Dili ve Edebiyatı",
  "Leh Dili ve Edebiyatı",
  "Lojistik",
  "Lojistik Yönetimi",
  "Maden Mühendisliği",
  "Madencilik Teknolojisi",
  "Mahkeme Büro Hizmetleri",
  "Makine",
  "Makine Mühendisliği",
  "Makine Resim ve Konstrüksiyonu",
  "Maliye",
  "Malzeme Bilimi ve Mühendisliği",
  "Malzeme Bilimi ve Nanoteknoloji Mühendisliği",
  "Malzeme Bilimi ve Teknolojileri",
  "Mantarcılık",
  "Marina ve Yat İşletmeciliği",
  "Marka İletişimi",
  "Matematik",
  "Matematik Mühendisliği",
  "Matematik ve Bilgisayar Bilimleri",
  "Matematik Öğretmenliği",
  "Medya ve Görsel Sanatlar",
  "Medya ve İletişim",
  "Mekatronik",
  "Mekatronik Mühendisliği",
  "Mermer Teknolojisi",
  "Metalurji",
  "Metalurji ve Malzeme Mühendisliği",
  "Meyve ve Sebze İşleme Teknolojisi",
  "Mimari Dekoratif Sanatlar",
  "Mimari Restorasyon",
  "Mimarlık",
  "Mobil Teknolojileri",
  "Mobilya ve Dekorasyon",
  "Moda Tasarımı",
  "Moda Yönetimi",
  "Moleküler Biyoloji ve Genetik",
  "Moleküler Biyoteknoloji",
  "Muhasebe ve Finans Yönetimi",
  "Muhasebe ve Finansman",
  "Muhasebe ve Vergi Uygulamaları",
  "Mühendislik ve Doğa Bilimleri Programları",
  "Müzecilik",
  "Müzik",
  "Müzik Öğretmenliği",
  "Nanobilim ve Nanoteknoloji",
  "Nanoteknoloji Mühendisliği",
  "Nükleer Enerji Mühendisliği",
  "Nükleer Teknoloji ve Radyasyon Güvenliği",
  "Nükleer Tıp Teknikleri",
  "Odyoloji",
  "Odyometri",
  "Ofis Teknolojileri ve Veri Yönetimi",
  "Okul Öncesi Öğretmenliği",
  "Optik ve Akustik Mühendisliği",
  "Optisyenlik",
  "Optoelektronik ve Elektro Optik Teknolojileri",
  "Organik Tarım",
  "Organik Tarım İşletmeciliği",
  "Orman Endüstrisi Mühendisliği",
  "Orman Mühendisliği",
  "Ormancılık ve Orman Ürünleri",
  "Ortez ve Protez",
  "Ortopedik Protez ve Ortez",
  "Otel Yöneticiliği",
  "Otobüs Kaptanlığı",
  "Otomotiv Gövde ve Yüzey İşlem Teknolojileri",
  "Otomotiv Mühendisliği",
  "Otomotiv Teknolojisi",
  "Otonom Sistemler Teknikerliği",
  "Otopsi Yardımcılığı",
  "Oyun Geliştirme ve Programlama",
  "Paramedik",
  "Pastacılık ve Ekmekçilik",
  "Patoloji Laboratuvar Teknikleri",
  "Pazarlama",
  "Perakende Satış ve Mağaza Yönetimi",
  "Perfüzyon",
  "Perfüzyon Teknikleri",
  "Petrol ve Doğalgaz Mühendisliği",
  "Peyzaj Mimarlığı",
  "Peyzaj ve Süs Bitkileri Yetiştiriciliği",
  "Pilotaj",
  "Podoloji",
  "Polimer Malzeme Mühendisliği",
  "Polimer Teknolojisi",
  "Politika ve Ekonomi",
  "Posta Hizmetleri",
  "Protohistorya ve Ön Asya Arkeolojisi",
  "Psikoloji",
  "Psikolojik Danışmanlık ve Rehberlik",
  "Radyo ve Televizyon Teknolojisi",
  "Radyo, Televizyon ve Sinema",
  "Radyoterapi",
  "Rafineri ve Petro-Kimya Teknolojisi",
  "Raylı Sistemler Elektrik ve Elektronik",
  "Raylı Sistemler İşletmeciliği",
  "Raylı Sistemler Makine Teknolojisi",
  "Raylı Sistemler Makinistliği",
  "Raylı Sistemler Mühendisliği",
  "Raylı Sistemler Yol Teknolojisi",
  "Rehberlik ve Psikolojik Danışmanlık",
  "Reklam Tasarımı ve İletişimi",
  "Reklamcılık",
  "Rekreasyon",
  "Rekreasyon Yönetimi",
  "Resim",
  "Robotik ve Yapay Zeka",
  "Rus Dili ve Edebiyatı",
  "Rusça Mütercim ve Tercümanlık",
  "Sahne Işık ve Ses Teknolojileri",
  "Sahne ve Dekor Tasarımı",
  "Sanal ve Artırılmış Gerçeklik",
  "Sanat Tarihi",
  "Sanat ve Kültür Yönetimi",
  "Sanat ve Sosyal Bilimler Programları",
  "Saç Bakımı ve Güzellik Hizmetleri",
  "Saç ve Güzellik Uygulamaları",
  "Sağlık Bilgi Sistemleri Teknikerliği",
  "Sağlık Kurumları İşletmeciliği",
  "Sağlık Turizmi İşletmeciliği",
  "Sağlık Yönetimi",
  "Seracılık",
  "Seramik ve Cam Tasarımı",
  "Sermaye Piyasası",
  "Seyahat İşletmeciliği",
  "Seyahat İşletmeciliği ve Turizm Rehberliği",
  "Siber Güvenlik",
  "Siber Güvenlik Analistliği ve Operatörlüğü",
  "Siber Güvenlik Mühendisliği",
  "Sigortacılık",
  "Sigortacılık ve Aktüerya Bilimleri",
  "Sigortacılık ve Risk Yönetimi",
  "Sigortacılık ve Sosyal Güvenlik",
  "Silah Sanayi Teknikerliği",
  "Sinema ve Dijital Medya",
  "Sinema ve Televizyon",
  "Sinoloji",
  "Sivil Hava Ulaştırma İşletmeciliği",
  "Sivil Havacılık Kabin Hizmetleri",
  "Sivil Savunma ve İtfaiyecilik",
  "Siyaset Bilimi",
  "Siyaset Bilimi ve Kamu Yönetimi",
  "Siyaset Bilimi ve Uluslararası İlişkiler",
  "Sondaj Teknolojisi",
  "Sosyal Bilgiler Öğretmenliği",
  "Sosyal Güvenlik",
  "Sosyal Hizmet",
  "Sosyal Hizmetler",
  "Sosyal Medya Yöneticiliği",
  "Sosyoloji",
  "Spor Bilimleri",
  "Spor Yöneticiliği",
  "Su Altı Kaynak Teknolojisi",
  "Su Altı Teknolojisi",
  "Su Bilimleri ve Mühendisliği",
  "Su ve Atık Yönetimi Teknikerliği",
  "Su Ürünleri Endüstrisi Mühendisliği",
  "Su Ürünleri İşleme Teknolojisi",
  "Su Ürünleri Mühendisliği",
  "Sulama Teknolojisi",
  "Sümeroloji",
  "Süryani Dili ve Edebiyatı",
  "Süt Teknolojisi",
  "Süt ve Besi Hayvancılığı",
  "Süt ve Ürünleri Teknolojisi",
  "Sınıf Öğretmenliği",
  "Sırp Dili ve Edebiyatı",
  "Tahribatsız Muayene",
  "Takı Tasarımı ve İmalatı",
  "Talaşlı Üretim Teknikerliği",
  "Tapu Kadastro",
  "Tapu ve Kadastro",
  "Tarih",
  "Tarih Öncesi Arkeolojisi",
  "Tarih Öğretmenliği",
  "Tarla Bitkileri",
  "Tarım Ekonomisi",
  "Tarım Makineleri",
  "Tarım Makineleri ve Teknolojileri",
  "Tarım Makineleri ve Teknolojileri Mühendisliği",
  "Tarım Teknolojisi",
  "Tarım Ticareti ve İşletmeciliği",
  "Tarımsal Biyoteknoloji",
  "Tarımsal Genetik Mühendisliği",
  "Tarımsal İşletmecilik",
  "Tarımsal Yapılar ve Sulama",
  "Teknoloji ve Bilgi Yönetimi",
  "Tekstil Mühendisliği",
  "Tekstil Tasarımı",
  "Tekstil Teknolojisi",
  "Tekstil ve Halı Makineleri",
  "Tekstil ve Moda Tasarımı",
  "Tele-Sağlık Teknikerliği",
  "Televizyon Haberciliği ve Programcılığı",
  "Tiyatro Eleştirmenliği ve Dramaturji",
  "Tohum Bilimi ve Teknolojisi",
  "Tohumculuk Teknolojisi",
  "Toprak Bilimi ve Bitki Besleme",
  "Turist Rehberliği",
  "Turizm Animasyonu",
  "Turizm İşletmeciliği",
  "Turizm Rehberliği",
  "Turizm ve Gastronomi Yönetimi Programları",
  "Turizm ve Otel İşletmeciliği",
  "Turizm ve Seyahat Hizmetleri",
  "Türk Dili ve Edebiyatı",
  "Türk Dili ve Edebiyatı Öğretmenliği",
  "Türk Halkbilimi",
  "Türk İslam Arkeolojisi",
  "Türkçe Öğretmenliği",
  "Tütün Eksperliği",
  "Tıbbi Dokümantasyon ve Sekreterlik",
  "Tıbbi Görüntüleme Teknikleri",
  "Tıbbi Laboratuvar Teknikleri",
  "Tıbbi Tanıtım ve Pazarlama",
  "Tıbbi ve Aromatik Bitkiler",
  "Tıbbi Veri İşleme Teknikerliği",
  "Tıp",
  "Ukrayna Dili ve Edebiyatı",
  "Ulaştırma ve Trafik Hizmetleri",
  "Uluslararası Finans",
  "Uluslararası Finans ve Bankacılık",
  "Uluslararası Girişimcilik",
  "Uluslararası İlişkiler",
  "Uluslararası İşletme Yönetimi",
  "Uluslararası Ticaret",
  "Uluslararası Ticaret ve Finansman",
  "Uluslararası Ticaret ve İşletmecilik",
  "Uluslararası Ticaret ve Lojistik",
  "Un ve Unlu Mamuller Teknolojisi",
  "Urdu Dili ve Edebiyatı",
  "Uzaktan Algılama ve Coğrafi Bilgi Sistemleri",
  "Uzay Bilimleri ve Teknolojileri",
  "Uzay Mühendisliği",
  "Uçak Bakım ve Onarım",
  "Uçak Elektrik ve Elektroniği",
  "Uçak Gövde ve Motor Bakımı",
  "Uçak Mühendisliği",
  "Uçak Teknolojisi",
  "Uçak ve Uzay Mühendisliği",
  "Uçuş Harekat Yöneticiliği",
  "Veri Bilimi ve Analitiği",
  "Veteriner",
  "Veterinerlik",
  "Web Tasarımı ve Kodlama",
  "Yaban Hayatı Ekolojisi ve Yönetimi",
  "Yapay Zeka Mühendisliği",
  "Yapay Zeka Operatörlüğü",
  "Yapay Zeka ve Makine Öğrenmesi",
  "Yapay Zeka ve Veri Mühendisliği",
  "Yapı Denetimi",
  "Yapı Ressamlığı",
  "Yapı Tesisat Teknolojisi",
  "Yapı Yalıtım Teknolojisi",
  "Yapı Yüzeyi Tasarım Teknikerliği",
  "Yat Kaptanlığı",
  "Yazılım Geliştirme",
  "Yazılım Mühendisliği",
  "Yağ Endüstrisi",
  "Yaşlı Bakımı",
  "Yeni Medya",
  "Yeni Medya ve Gazetecilik",
  "Yeni Medya ve İletişim",
  "Yenilenebilir Enerji Teknikerliği",
  "Yerel Yönetimler",
  "Yeşil ve Ekolojik Bina Teknikerliği",
  "Yiyecek ve İçecek İşletmeciliği",
  "Yunan Dili ve Edebiyatı",
  "Yönetim Bilimleri Programları",
  "Yönetim Bilişim Sistemleri",
  "Zaza Dili ve Edebiyatı",
  "Zeytincilik ve Zeytin İşleme Teknolojisi",
  "Ziraat Mühendisliği",
  "Ziraat Mühendisliği Programları",
  "Zootekni",
  "Çalışma Ekonomisi ve Endüstri İlişkileri",
  "Çay Tarımı ve İşleme Teknolojisi",
  "Çağdaş Türk Lehçeleri ve Edebiyatları",
  "Çağdaş Yunan Dili ve Edebiyatı",
  "Çağrı Merkezi Hizmetleri",
  "Çerkez Dili ve Edebiyatı",
  "Çerkez Dili ve Kültürü",
  "Çeviribilimi",
  "Çevre Koruma ve Kontrol",
  "Çevre Mühendisliği",
  "Çevre Sağlığı",
  "Çevre Sağlığı ve Çevresel Risk Yönetimi Teknikerliği",
  "Çevresel Ölçüm ve İzleme Sistemleri Teknikerliği",
  "Çim Alan Tesisi ve Yönetimi",
  "Çin Dili ve Edebiyatı",
  "Çince Mütercim ve Tercümanlık",
  "Çini Sanatı ve Tasarımı",
  "Çizgi Film ve Animasyon",
  "Çocuk Gelişimi",
  "Çocuk Koruma ve Bakım Hizmetleri",
  "Çok Boyutlu Modelleme ve Animasyon",
  "Ön-Yüz Yazılım Geliştirme",
  "Özel Eğitim Öğretmenliği",
  "Özel Güvenlik ve Koruma",
  "Üretimde Kalite Kontrol",
  "Şarap Üretim Teknolojisi",
  "Şehir ve Bölge Planlama",
]);
