const rawCityUniversities = {
  "Adana": ["Çukurova Üniversitesi", "Adana Alparslan Türkeş Bilim ve Teknoloji Üniversitesi"],
  "Adıyaman": ["Adıyaman Üniversitesi"],
  "Afyonkarahisar": ["Afyon Kocatepe Üniversitesi", "Afyonkarahisar Sağlık Bilimleri Üniversitesi"],
  "Ağrı": ["Ağrı İbrahim Çeçen Üniversitesi"],
  "Aksaray": ["Aksaray Üniversitesi"],
  "Amasya": ["Amasya Üniversitesi"],
  "Ankara": [
    "Ankara Üniversitesi",
    "Hacettepe Üniversitesi",
    "Orta Doğu Teknik Üniversitesi",
    "Gazi Üniversitesi",
    "Ankara Yıldırım Beyazıt Üniversitesi",
    "Bilkent Üniversitesi",
    "Başkent Üniversitesi",
    "TOBB Ekonomi ve Teknoloji Üniversitesi",
    "Çankaya Üniversitesi",
    "TED Üniversitesi"
  ],
  "Antalya": ["Akdeniz Üniversitesi", "Alanya Alaaddin Keykubat Üniversitesi", "Antalya Bilim Üniversitesi"],
  "Ardahan": ["Ardahan Üniversitesi"],
  "Artvin": ["Artvin Çoruh Üniversitesi"],
  "Aydın": ["Aydın Adnan Menderes Üniversitesi"],
  "Balıkesir": ["Balıkesir Üniversitesi", "Bandırma Onyedi Eylül Üniversitesi"],
  "Bartın": ["Bartın Üniversitesi"],
  "Batman": ["Batman Üniversitesi"],
  "Bayburt": ["Bayburt Üniversitesi"],
  "Bilecik": ["Bilecik Şeyh Edebali Üniversitesi"],
  "Bingöl": ["Bingöl Üniversitesi"],
  "Bitlis": ["Bitlis Eren Üniversitesi"],
  "Bolu": ["Bolu Abant İzzet Baysal Üniversitesi"],
  "Burdur": ["Burdur Mehmet Akif Ersoy Üniversitesi"],
  "Bursa": ["Bursa Uludağ Üniversitesi", "Bursa Teknik Üniversitesi"],
  "Çanakkale": ["Çanakkale Onsekiz Mart Üniversitesi"],
  "Çankırı": ["Çankırı Karatekin Üniversitesi"],
  "Çorum": ["Hitit Üniversitesi"],
  "Denizli": ["Pamukkale Üniversitesi"],
  "Diyarbakır": ["Dicle Üniversitesi"],
  "Düzce": ["Düzce Üniversitesi"],
  "Edirne": ["Trakya Üniversitesi"],
  "Elazığ": ["Fırat Üniversitesi"],
  "Erzincan": ["Erzincan Binali Yıldırım Üniversitesi"],
  "Erzurum": ["Atatürk Üniversitesi", "Erzurum Teknik Üniversitesi"],
  "Eskişehir": ["Anadolu Üniversitesi", "Eskişehir Osmangazi Üniversitesi", "Eskişehir Teknik Üniversitesi"],
  "Gaziantep": ["Gaziantep Üniversitesi", "Hasan Kalyoncu Üniversitesi", "SANKO Üniversitesi"],
  "Giresun": ["Giresun Üniversitesi"],
  "Gümüşhane": ["Gümüşhane Üniversitesi"],
  "Hakkâri": ["Hakkâri Üniversitesi"],
  "Hatay": ["Hatay Mustafa Kemal Üniversitesi", "İskenderun Teknik Üniversitesi"],
  "Iğdır": ["Iğdır Üniversitesi"],
  "Isparta": ["Süleyman Demirel Üniversitesi", "Isparta Uygulamalı Bilimler Üniversitesi"],
  "İstanbul": [
      // Devlet Üniversiteleri
    "İstanbul Üniversitesi",
    "İstanbul Üniversitesi-Cerrahpaşa",
    "İstanbul Teknik Üniversitesi",
    "Boğaziçi Üniversitesi",
    "Marmara Üniversitesi",
    "Yıldız Teknik Üniversitesi",
    "Galatasaray Üniversitesi",
    "Mimar Sinan Güzel Sanatlar Üniversitesi",
    "İstanbul Medeniyet Üniversitesi",
    "Türk-Alman Üniversitesi",
    "Sağlık Bilimleri Üniversitesi",
    "İstanbul Galata Üniversitesi",

    // Vakıf Üniversiteleri
    "Koç Üniversitesi",
    "Sabancı Üniversitesi",
    "Bahçeşehir Üniversitesi",
    "Yeditepe Üniversitesi",
    "İstanbul Bilgi Üniversitesi",
    "İstanbul Aydın Üniversitesi",
    "İstanbul Okan Üniversitesi",
    "İbn Haldun Üniversitesi",
    "İstinye Üniversitesi",
    "Maltepe Üniversitesi",
    "Üsküdar Üniversitesi",
    "Acıbadem Mehmet Ali Aydınlar Üniversitesi",
    "Altınbaş Üniversitesi",
    "Beykent Üniversitesi",
    "Beykoz Üniversitesi",
    "Bezm-i Âlem Vakıf Üniversitesi",
    "Biruni Üniversitesi",
    "Demiroğlu Bilim Üniversitesi",
    "Doğuş Üniversitesi",
    "Fatih Sultan Mehmet Vakıf Üniversitesi",
    "Fenerbahçe Üniversitesi",
    "Haliç Üniversitesi",
    "Işık Üniversitesi",
    "İstanbul Nişantaşı Üniversitesi",
    "İstanbul Sağlık ve Teknoloji Üniversitesi",
    "İstanbul 29 Mayıs Üniversitesi",
    "İstanbul Arel Üniversitesi",
    "İstanbul Atlas Üniversitesi",
    "İstanbul Esenyurt Üniversitesi",
    "İstanbul Gedik Üniversitesi",
    "İstanbul Gelişim Üniversitesi",
    "İstanbul Kent Üniversitesi",
    "İstanbul Kültür Üniversitesi",
    "İstanbul Medipol Üniversitesi",
    "İstanbul Rumeli Üniversitesi",
    "İstanbul Sabahattin Zaim Üniversitesi",
    "İstanbul Ticaret Üniversitesi",
    "İstanbul Topkapı Üniversitesi",
    "İstanbul Yeni Yüzyıl Üniversitesi",
    "Kadir Has Üniversitesi",
    "Lokman Hekim Üniversitesi",
    "Mef Üniversitesi",
    "Özyeğin Üniversitesi",
    "Piri Reis Üniversitesi",
    "Torun Üniversitesi",

    // Vakıf Meslek Yüksekokulları (üniversiteye bağlı olmayan)
    "Ataşehir Adıgüzel Meslek Yüksekokulu",
    "Avrupa Meslek Yüksekokulu",
    "İstanbul Sağlık ve Sosyal Bilimler Meslek Yüksekokulu",
    "İstanbul Şişli Meslek Yüksekokulu"  ],
  "İzmir": [
    "Ege Üniversitesi",
    "Dokuz Eylül Üniversitesi",
    "İzmir Yüksek Teknoloji Enstitüsü",
    "İzmir Kâtip Çelebi Üniversitesi",
    "İzmir Bakırçay Üniversitesi",
    "İzmir Demokrasi Üniversitesi",
    "Yaşar Üniversitesi",
    "İzmir Ekonomi Üniversitesi"
  ],
  "Kahramanmaraş": ["Kahramanmaraş Sütçü İmam Üniversitesi", "Kahramanmaraş İstiklal Üniversitesi"],
  "Karabük": ["Karabük Üniversitesi"],
  "Karaman": ["Karamanoğlu Mehmetbey Üniversitesi"],
  "Kars": ["Kafkas Üniversitesi"],
  "Kastamonu": ["Kastamonu Üniversitesi"],
  "Kayseri": ["Erciyes Üniversitesi", "Abdullah Gül Üniversitesi", "Nuh Naci Yazgan Üniversitesi"],
  "Kilis": ["Kilis 7 Aralık Üniversitesi"],
  "Kırıkkale": ["Kırıkkale Üniversitesi"],
  "Kırklareli": ["Kırklareli Üniversitesi"],
  "Kırşehir": ["Kırşehir Ahi Evran Üniversitesi"],
  "Kocaeli": ["Kocaeli Üniversitesi", "Gebze Teknik Üniversitesi"],
  "Konya": ["Selçuk Üniversitesi", "Necmettin Erbakan Üniversitesi", "Konya Teknik Üniversitesi", "KTO Karatay Üniversitesi"],
  "Kütahya": ["Kütahya Dumlupınar Üniversitesi", "Kütahya Sağlık Bilimleri Üniversitesi"],
  "Malatya": ["İnönü Üniversitesi", "Malatya Turgut Özal Üniversitesi"],
  "Manisa": ["Manisa Celal Bayar Üniversitesi"],
  "Mardin": ["Mardin Artuklu Üniversitesi"],
  "Mersin": ["Mersin Üniversitesi", "Tarsus Üniversitesi", "Çağ Üniversitesi"],
  "Muğla": ["Muğla Sıtkı Koçman Üniversitesi"],
  "Muş": ["Muş Alparslan Üniversitesi"],
  "Nevşehir": ["Nevşehir Hacı Bektaş Veli Üniversitesi"],
  "Niğde": ["Niğde Ömer Halisdemir Üniversitesi"],
  "Ordu": ["Ordu Üniversitesi"],
  "Osmaniye": ["Osmaniye Korkut Ata Üniversitesi"],
  "Rize": ["Recep Tayyip Erdoğan Üniversitesi"],
  "Sakarya": ["Sakarya Üniversitesi", "Sakarya Uygulamalı Bilimler Üniversitesi"],
  "Samsun": ["Ondokuz Mayıs Üniversitesi", "Samsun Üniversitesi"],
  "Siirt": ["Siirt Üniversitesi"],
  "Sinop": ["Sinop Üniversitesi"],
  "Sivas": ["Sivas Cumhuriyet Üniversitesi", "Sivas Bilim ve Teknoloji Üniversitesi"],
  "Şanlıurfa": ["Harran Üniversitesi"],
  "Şırnak": ["Şırnak Üniversitesi"],
  "Tekirdağ": ["Tekirdağ Namık Kemal Üniversitesi"],
  "Tokat": ["Tokat Gaziosmanpaşa Üniversitesi"],
  "Trabzon": ["Karadeniz Teknik Üniversitesi", "Trabzon Üniversitesi"],
  "Tunceli": ["Munzur Üniversitesi"],
  "Uşak": ["Uşak Üniversitesi"],
  "Van": ["Van Yüzüncü Yıl Üniversitesi"],
  "Yalova": ["Yalova Üniversitesi"],
  "Yozgat": ["Yozgat Bozok Üniversitesi"],
  "Zonguldak": ["Zonguldak Bülent Ecevit Üniversitesi"],

  // KKTC (Kuzey Kıbrıs Türk Cumhuriyeti)
  "Lefkoşa (KKTC)": [
    "Yakın Doğu Üniversitesi",
    "Uluslararası Kıbrıs Üniversitesi",
    "Rauf Denktaş Üniversitesi"
  ],
  "Gazimağusa (KKTC)": ["Doğu Akdeniz Üniversitesi"],
  "Girne (KKTC)": [
    "Girne Amerikan Üniversitesi",
    "Bahçeşehir Kıbrıs Üniversitesi",
    "Final International University",
    "Arkın Yaratıcı Sanatlar ve Tasarım Üniversitesi",
    "Kıbrıs İlim Üniversitesi"
  ],
  "Güzelyurt (KKTC)": [
    "Orta Doğu Teknik Üniversitesi Kuzey Kıbrıs Kampüsü",
    "Kıbrıs Sağlık ve Toplum Bilimleri Üniversitesi"
  ],
  "Lefke (KKTC)": ["Lefke Avrupa Üniversitesi"]
};

function sortByTurkishLocale(values) {
  return [...values].sort((a, b) => a.localeCompare(b, "tr"));
}

const cityUniversities = Object.fromEntries(
  Object.entries(rawCityUniversities)
    .sort(([cityA], [cityB]) => cityA.localeCompare(cityB, "tr"))
    .map(([city, universities]) => [city, Object.freeze(sortByTurkishLocale(new Set(universities)))])
);

export const CITY_UNIVERSITIES = Object.freeze(cityUniversities);
export const TURKEY_CITIES = Object.freeze(Object.keys(CITY_UNIVERSITIES));
